server:
  port: 9002
spring:
  application:
    name: remote-resource-server
  profiles:
    active: dev
logging:
  level:
    org.springframework: DEBUG
security:
  oauth2:
    resource:
      #id: oauth2-resource
      token-info-uri: http://localhost:9001/oauth/check_token #远程认证
      prefer-token-info: true
    client:
      client-id: client #远程认证
      client-secret: secret #远程认证
      #access-token-uri: http://localhost:9001/oauth/token
      #user-authorization-uri: http://localhost:9001/oauth/authorize










