spring:
  application:
    name: fegin-provide-service
server:
  port: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 20
  instance:
    prefer-ip-address: true

