server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true  #有些数据库连接的时候有超时限制（mysql连接在8小时后断开），或者由于网络中断等原因，连接池的连接会出现失效的情况，这时候设置一个testWhileIdle参数为true，可以保证连接池内部定时检测连接的可用性，不可用的连接会被抛弃或者重建，最大情况的保证从连接池中得到的Connection对象是可用的
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000 #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    min-evictable-idle-time-millis: 1800000 #连接池空闲连接的有效时间 ，设置30分钟
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
