server:
  port: 3000
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data
