server:
  port: 4000
spring:
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        #max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  cache:
    type: redis
  zookeeper:
    zkServers: zookeeper-cluster-node1.test.svc.k8s.syf.com:2181,zookeeper-cluster-node2.test.svc.k8s.syf.com:2181,zookeeper-cluster-node3.test.svc.k8s.syf.com:2181









